### ISSUE TITLE
The repository don't work on repl

### ISSUE THREAD

**Issue by D4ng3rus** [XKMR/discord-link-phishing#3]
The repository don't work for me, i didn't change the code, i only fork this on replt and i run it, but this don't work.
Pls help me :c
![Captura de pantalla 2021-12-01 073958](https://user-images.githubusercontent.com/95354685/144236061-8424c188-0b6f-43a2-aefc-47b3c7e70456.png)
![Captura de pantalla 2021-12-01 074222](https://user-images.githubusercontent.com/95354685/144236388-e1efaf45-5ff8-4ace-9c41-c977cf05f19e.png)

**Comment by Dripfy** [comment]
I could help you if you could make this public and send me and i will fork it. And then after send me an invite to the replit

**Comment by XKMR** [comment]
hi! sorry for the delay.
I think the problem is: you are not adding the "/gift/HJ9fh9hGfgfijh93/" or "/gift/HJ9fh9hGfgfijh93/login/" to the address. I mean if your domain is "domain.com", you should change it to "domain.com/gift/HJ9fh9hGfgfijh93/" or "domain.com/gift/HJ9fh9hGfgfijh93/login". I built to so it won't work if you don't add it. let me know if this helped or no.

**Comment by XKMR** [comment]
and if you don't add it, it will send you to "discord.com" (discord's official website)
for... not being sus.

**Comment by XKMR** [comment]
I don't know why that is happening on repl. but I recommend you to use profreehost.com (NOT ADVERTISING). it's free and it has ftp and php. I personally use it.

**Comment by XKMR** [comment]
and also check if php is compatible with repl.

**Comment by XKMR** [comment]
sorry for the delay
here's the solution:
the default web page is not set to index.php. so add "/index.php" after the "/login"

**Comment by XKMR** [comment]
let me know if it worked.

**Comment by DOKKAEBIx** [comment]
Im having the same issue

**Comment by vidgix** [comment]
> sorry for the delay here's the solution: the default web page is not set to index.php so add "/index.php" after the "/login"

with da "/"?

**Comment by XxAcesXx** [comment]
> let me know if it worked.

Brooo i cant Get it Please Can i Invite you On My panel

**Comment by XxAcesXx** [comment]
Broo do a Screen record how to run it

**Comment by XKMR** [comment]
https://user-images.githubusercontent.com/58393719/163674974-8329c0b7-3877-4cb4-964e-4290c446bc79.mp4

**Comment by XKMR** [comment]
I made a new update. see if it's fixed

**Comment by XKMR** [comment]
I fixed it, if it still does not work on repl, you can find another free hosting platform
