### ISSUE TITLE
the images are not showing 

### ISSUE THREAD

**Issue by RaymanX10** [XKMR/discord-link-phishing#5]
http://rayman.x10.mx/login/ heres the page

**Comment by XKMR** [comment]
sorry for the delay

![image](https://user-images.githubusercontent.com/58393719/163674432-0fd7493b-a629-4172-88a3-ef39bfdfd5fe.png)

**Comment by XKMR** [comment]
so, I made an update on the code, see if it's fixed (also check if your host supports PHP)

**Comment by XKMR** [comment]
The issue is fixed
